server.port: 8080

application:
  exchange-rate-queue: "exchange.rate."
  coin-queue: "coin."
  quote-expiration-time-minutes: 10
  clients:
    coin-market-cap:
      url: https://pro-api.coinmarketcap.com/
      key: secret

spring:
  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin
  datasource:
    url: jdbc:postgresql://db:5432/coinmarket-api
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate.ddl-auto: none
  liquibase:
    enabled: true