server.port: 8080

application:
  exchange-rate-queue: "exchange.rate."
  coin-queue: "coin."
  quote-expiration-time-minutes: 10
  clients:
    coin-market-cap:
      url: https://pro-api.coinmarketcap.com/
      key: secret

spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: secret
    password: secret